# Generated by Django 4.1.5 on 2023-01-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('product_name', models.CharField(help_text='Наименование продукта', max_length=500, verbose_name='Наименование продукта')),
                ('product_description', models.CharField(help_text='Описание товара', max_length=1000, verbose_name='Описание товара')),
                ('product_price', models.FloatField(help_text='Стоимость продукта', verbose_name='Стоимость продукта')),
                ('product_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
